[book]
title = "Cangjie Std API"
language = "cn"
src = "src"

[build]
build-dir = "./output/std_api_zh"
create-missing = true

[output.html.fold]
enable = true # whether or not to enable section folding
level = 0     # the depth to start folding

[output.html.search]
limit-results = 200
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor._0_table_joiner]
command = "python3 scripts/table.py"

[preprocessor._1_blockquote_admonish]
command = "python3 scripts/blockquote_admonish.py"

[preprocessor._2_example_fold]
command = "python3 scripts/example_fold.py"

[preprocessor.pagetoc]
command = "python3 scripts/pagetoc_wrapper.py"
renderer = ["html"]

[output.html]
default-theme = "latte"
preferred-dark-theme = "macchiato"
no-section-label = true
admonitions = true
additional-css = [
  "./theme/pagetoc.css",
  "./theme/catppuccin.css",
  "./theme/table-fullwidth.css",
  "./theme/example-fold.css",
  "./theme/custom_style.css",
]
additional-js = [
  "./theme/pagetoc.js",
  "./theme/elasticlunr.js",
  "./theme/fzf.umd.js",
  "./theme/hljs-cangjie.js",
  "./theme/searcher-custom.js",
]
